Fix broken build of SCL in COPR
Happens only in COPR.

Addressing:
+ scl enable ruby193 '
rake test --trace
'
** Invoke test (first_time)
** Execute test
rake aborted!
undefined method `attach_function' for OpenSCAP:Module
/builddir/build/BUILD/openscap-0.4.0/lib/openscap/source.rb:56:in `<module:OpenSCAP>'
/builddir/build/BUILD/openscap-0.4.0/lib/openscap/source.rb:12:in `<top (required)>'
/opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/builddir/build/BUILD/openscap-0.4.0/test/xccdf/testresult_test.rb:12:in `<top (required)>'
/opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/builddir/build/BUILD/openscap-0.4.0/Rakefile:8:in `block (2 levels) in <top (required)>'