typo: Add missing colons
Addressing:
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: 'openscap (= 0.0.1)' requires 'ffi>= 1.4.0 (>= 0)'